"""add warehouse_id to products (nullable)

Revision ID: 223f6ff55bd2
Revises: f93d6dc49130
Create Date: 2025-08-29 18:27:55.539261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223f6ff55bd2'
down_revision = 'f93d6dc49130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index('ix_products_wh_name', ['warehouse_id', 'name'], unique=False)
        batch_op.create_unique_constraint('uq_products_wh_name', ['warehouse_id', 'name'])
        batch_op.create_foreign_key(batch_op.f('fk_products_warehouse_id_warehouse'), 'warehouse', ['warehouse_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_name'))
        batch_op.create_unique_constraint(batch_op.f('uq_warehouse_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_warehouse_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_warehouses_name'), ['name'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_warehouse_id_warehouse'), type_='foreignkey')
        batch_op.drop_constraint('uq_products_wh_name', type_='unique')
        batch_op.drop_index('ix_products_wh_name')
        batch_op.drop_index(batch_op.f('ix_products_warehouse_id'))
        batch_op.drop_column('warehouse_id')

    # ### end Alembic commands ###
