"""warehouse_id not null + unique per warehouse

Revision ID: 41693267d20e
Revises: 223f6ff55bd2
Create Date: 2025-08-29 18:31:37.147222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41693267d20e'
down_revision = '223f6ff55bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
