"""add stock_movement, transfer, transfer_item

Revision ID: a52555765231
Revises: 90100fda535c
Create Date: 2025-09-09 14:21:05.002098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52555765231'
down_revision = '90100fda535c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY_TO_DELIVER', 'IN_TRANSIT', 'DELIVERED', 'RECEIVED', name='transfer_status'), nullable=False),
    sa.Column('source_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('dest_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_by_source_user_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_dest_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('source_warehouse_id <> dest_warehouse_id', name='ck_transfer_src_ne_dest'),
    sa.ForeignKeyConstraint(['confirmed_by_dest_user_id'], ['users.id'], name=op.f('fk_transfers_confirmed_by_dest_user_id_users')),
    sa.ForeignKeyConstraint(['confirmed_by_source_user_id'], ['users.id'], name=op.f('fk_transfers_confirmed_by_source_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_transfers_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['dest_warehouse_id'], ['warehouse.id'], name=op.f('fk_transfers_dest_warehouse_id_warehouse')),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouse.id'], name=op.f('fk_transfers_source_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfers'))
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_confirmed_by_dest_user_id'), ['confirmed_by_dest_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_confirmed_by_source_user_id'), ['confirmed_by_source_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_dest_warehouse_id'), ['dest_warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_source_warehouse_id'), ['source_warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_status'), ['status'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IN', 'OUT', 'ADJUST_ABS', 'ADJUST_REL', name='stockmovement_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('related_transfer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_stock_movements_actor_user_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_movements_product_id_products')),
    sa.ForeignKeyConstraint(['related_transfer_id'], ['transfers.id'], name=op.f('fk_stock_movements_related_transfer_id_transfers')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_stock_movements_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_related_transfer_id'), ['related_transfer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('transfer_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_transfer_item_qty_pos'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_transfer_items_product_id_products')),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_transfer_items_transfer_id_transfers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_items')),
    sa.UniqueConstraint('transfer_id', 'product_id', name='uq_transfer_item_per_product')
    )
    with op.batch_alter_table('transfer_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_items_transfer_id'), ['transfer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_items_transfer_id'))
        batch_op.drop_index(batch_op.f('ix_transfer_items_product_id'))

    op.drop_table('transfer_items')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_related_transfer_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_created_at'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_actor_user_id'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_status'))
        batch_op.drop_index(batch_op.f('ix_transfers_source_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_dest_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_confirmed_by_source_user_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_confirmed_by_dest_user_id'))

    op.drop_table('transfers')
    # ### end Alembic commands ###
