"""Add to WareHouse is_active and timestamp

Revision ID: f93d6dc49130
Revises: 99f588a4eb0d
Create Date: 2025-08-29 17:13:33.345714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93d6dc49130'
down_revision = '99f588a4eb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_warehouse")
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_warehouse_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_warehouses_name', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.drop_index('ix_warehouses_name')
        batch_op.drop_index(batch_op.f('ix_warehouse_is_active'))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')

    op.create_table('_alembic_tmp_warehouse',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
